######################################################################
# Automatically generated by qmake (2.01a) ??? 31. ?? 15:29:47 2008
######################################################################
QT+=widgets
TEMPLATE = app
TARGET = image
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h workarea.h
SOURCES += main.cpp mainwindow.cpp workarea.cpp
